base/urls.py
from django.urls import path, include

from . import views
from .views import home, sobre

app_name = "base"

urlpatterns = [
    path("contas/", include("django.contrib.auth.urls")),
    path("contas/registrar/", views.registrar, name="register"),
    path("", home, name="home"),
    path("sobre/", sobre, name="sobre")
]

carrinho/urls.py
from django.urls import path
from carrinho import views

app_name = "carrinho"

urlpatterns = [
    path("ver/", views.ver, name="ver"),
    path("adicionar/<int:pk>", views.adicionar, name="adicionar"),
    path("remover/<int:pk>", views.remover, name="remover"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from base import urls as base_urls
from livro import urls as livro_urls
from carrinho import urls as carrinho_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(base_urls)),
    path("livro/", include(livro_urls)),
    path("carrinho/", include(carrinho_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livro/urls.py
from django.urls import path

from . import views

app_name = "livro"

urlpatterns = [
    path("buscar", views.buscar, name="buscar"),
    path("todos", views.todos, name="todos"),
    path("novo", views.novo, name="novo"),
    path("excluir/<int:pk>", views.excluir, name="excluir"),
    path("atualizar/<int:pk>", views.atualizar, name="atualizar"),
    path("vermais/<int:pk>", views.vermais, name="vermais"),
]

base/models.py
from django.db import models

# Create your models here.

carrinho/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum, F

from livro.models import Livro


class Endereco(models.Model):
    rua = models.CharField("Rua", max_length=200, null=True)
    numero = models.CharField("Número", max_length=10, null=True)
    complemento = models.CharField(
        "Número",
        max_length=20,
        null=True,
        blank=True
    )
    bairro = models.CharField("Bairro", max_length=100, null=True)
    cidade = models.CharField("Cidade", max_length=50, null=True)
    estado = models.CharField("Estado", max_length=100, null=True)
    cep = models.CharField("CEP", max_length=9, null=True)

    class Meta:
        verbose_name_plural = "Endereços"

    def __str__(self):
        return self.rua


class Cliente(models.Model):
    user = models.OneToOneField(
        User,
        related_name='cliente',
        null=True,
        on_delete=models.CASCADE
    )
    nome = models.CharField("Nome completo", max_length=200)
    data_nascimento = models.DateField(
        "Data nascimento",
        blank=True,
        null=True
    )
    cpf = models.CharField("CPF", max_length=18, null=True)
    endereco = models.ForeignKey(
        Endereco,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name = "Endereco",
    )
    telefone = models.CharField(
        "Nº telefone celular",
        max_length=11,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name_plural = "Clientes"

    def __str__(self):
        return self.nome


class Carrinho(models.Model):
    cliente = models.ForeignKey(
        Cliente,
        on_delete=models.CASCADE,
        verbose_name="Cliente",
    )

    class Meta:
        verbose_name_plural = "Carrinhos"

    def __str__(self):
        if self.cliente:
            return self.cliente.nome

        return self.id

    @property
    def total(self) -> float:
        return self.itens.aggregate(
            total=Sum(F('quantidade') * F('preco'))
        )['total']


class ItemCarrinho(models.Model):
    carrinho = models.ForeignKey(
        Carrinho,
        related_name='itens',
        on_delete=models.CASCADE,
        verbose_name="Item do carrinho",
    )
    livro = models.ForeignKey(
        Livro,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Livro",
    )
    quantidade = models.FloatField('Quantidade', null=True)
    preco = models.FloatField('Preço', null=True)

    class Meta:
        verbose_name_plural = "Itens do carrinho"

    def __str__(self):
        if self.carrinho and self.carrinho.cliente:
            return self.carrinho.cliente.nome

        return self.id

base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NovoUsuarioForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NovoUsuarioForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

base/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import render, redirect

from base.forms import NovoUsuarioForm
from livro.models import Livro


def home(request):
    livros = Livro.objects.all()[:5]

    dados = {"livros": livros}

    return render(request, "base/home.html", dados)


def sobre(request):


    return render(request, "base/sobre.html")

def registrar(request):
    form = NovoUsuarioForm(request.POST or None)

    if form.is_valid():
        user = form.save()
        login(request, user)
        messages.success(request, "Usuário registrado com sucesso.")

        return redirect("base:login")

    messages.error(request, "Falha ao registrar usuário. Informações inválidas.")

    return render(
        request=request,
        template_name="registration/registrar.html",
        context={"form": form}
    )

carrinho/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from carrinho.models import Carrinho, ItemCarrinho, Cliente
from livro.models import Livro


@login_required(login_url="base:login")
def ver(request):
    if not request.user.is_authenticated:
        return redirect("base:login")

    carrinho = Carrinho.objects.filter(cliente__user=request.user).last()

    dados = {
        "carrinho": carrinho,
        "itens": carrinho.itens.all if carrinho else []
    }

    return render(request, "carrinho/ver.html", dados)


@login_required(login_url="base:login")
def adicionar(request, pk):
    cliente, _ = Cliente.objects.get_or_create(user=request.user)

    carrinho = Carrinho.objects.filter(cliente=cliente).last()

    if not carrinho:
        carrinho = Carrinho.objects.create(cliente=cliente)

    livro = Livro.objects.get(pk=pk)

    item_no_carrinho = carrinho.itens.filter(livro=livro).first()

    if item_no_carrinho:
        item_no_carrinho.quantidade += 1
        item_no_carrinho.save()
    else:
        ItemCarrinho.objects.create(
            carrinho=carrinho,
            livro=livro,
            quantidade=1,
            preco=livro.valor,
        )

    return redirect("carrinho:ver")


@login_required(login_url="base:login")
def remover(request, pk):
    carrinho = Carrinho.objects.filter(cliente__user=request.user).last()

    if not carrinho:
        carrinho = Carrinho.objects.create(cliente__user=request.user)

    livro = Livro.objects.get(pk=pk)

    item_no_carrinho = carrinho.itens.filter(livro=livro).first()

    if item_no_carrinho:
        item_no_carrinho.delete()

    return redirect("carrinho:ver")

base/templates/carrinho/carrinho.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Carrinho{% endblock %}

{% block cabecalho %}
{% include "base/cabecalho.html" %}
{% endblock %}

{% block rodape %}
{% include "base/rodape.html" %}
{% endblock %}

{% block content %}
    <div class="container">
         <div class="row">
            <div class="col-3">
                <h5 class="card-title">Produto</h5>
            </div>
            <div class="col-3">

            </div>
            <div class="col-3">
                 <span class="card-text">Valor</span>
            </div>
            <div class="col-3">
                <h5 class="card-title">Quantidade</h5>
            </div>
        </div>
        {% for livro in livros %}
        <div class="row my-2 py-2 border-top border-bottom   ">
            <div class="col-3">
                <div class="list-group ">
                  <img src="..." class="float-left" alt="...">
                </div>
            </div>
            <div class="col-3">
                <h5 class="card-title">{{livro.titulo}}</h5>
            </div>
            <div class="col-3">
                 <span class="card-text">${{livro.valor}}</span>
            </div>
            <div class="col-3">
                <a href="#"><button class=" btn-secondary "> +</button></a>
                <span class="text-center py-1 mx-2 text-align">0 </span>
                <a href="#"><button class=" btn-secondary px-2 "> -</button></a>
            </div>
        </div>
         {% endfor %}

        <a href="{% url 'url_novo' %}"><button class="btn btn-success mt-3" type="submit">Adicionar</button></a>
    </div>
    {% endblock %}

base/templates/carrinho/itens.html
{% load humanize %}

{% for item in itens %}
    <div class="card mb-3">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <div class="d-flex flex-row align-items-center">
                    <div class="flex-shrink-0">
                        <img src="{{ item.livro.imagem.url }}"
                             class="img-fluid rounded-3" alt="Shopping item"
                             style="width: 65px;">
                    </div>
                    <div class="mx-3">
                        <h5>{{ item.livro.titulo }}</h5>
                        <p class="small mb-0">{{ item.livro.descricao }}</p>
                    </div>
                </div>
                <div class="d-flex flex-row align-items-center">
                    <div class="text-end" style="width: 2rem">
                        <h5 class="fw-normal mb-0">{{ item.quantidade|floatformat:0|intcomma }}</h5>
                    </div>
                    <div class="mx-2">
                        <h5 class="fw-normal mb-0"><i class="bi bi-x"></i></h5>
                    </div>
                    <div style="width: 6rem">
                        <h5 class="mb-0">R$ {{ item.preco|floatformat:2|intcomma }}</h5>
                    </div>
                    <a href="{% url 'carrinho:remover' item.livro.id %}"
                       style="color: rgb(206, 206, 206); --darkreader-inline-color: #c9c4bd;"
                       data-darkreader-inline-color=""><i class="bi bi-trash3-fill"></i></a>
                </div>
            </div>
        </div>
    </div>
{% endfor % %}

base/templates/carrinho/pagamento.html
{% load humanize %}

<div class="col-lg-5">
    <div class="card rounded-3">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h5 class="mb-0">Pagamento em cartão de crédito</h5>
                <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-6.webp"
                     class="img-fluid rounded-3" style="width: 45px;" alt="Avatar">
            </div>

            <form class="mt-4">
                <div class="form-outline form-white mb-4">
                    <input type="text" id="typeName"
                           class="form-control form-control-lg" size="17"
                           placeholder="Cardholder's Name"/>
                    <label class="form-label mt-1" for="typeName">
                        <small class="text-muted">Nome no cartão</small>
                    </label>
                </div>

                <div class="form-outline form-white mb-4">
                    <input type="text" id="typeText"
                           class="form-control form-control-lg" size="17"
                           placeholder="1234 5678 9012 3457" minlength="19"
                           maxlength="19"/>
                    <label class="form-label mt-1" for="typeText">
                        <small class="text-muted"> Número do cartão</small>
                    </label>
                </div>

                <div class="row mb-4">
                    <div class="col-md-6">
                        <div class="form-outline form-white">
                            <input type="text" id="typeExp"
                                   class="form-control form-control-lg"
                                   placeholder="MM/YYYY" size="7" id="exp"
                                   minlength="7" maxlength="7"/>
                            <label class="form-label mt-1" for="typeExp">
                                <small class="text-muted">Expiração</small>
                            </label>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-outline form-white">
                            <input type="password" id="typeText"
                                   class="form-control form-control-lg"
                                   placeholder="&#9679;&#9679;&#9679;" size="1"
                                   minlength="3" maxlength="3"/>
                            <label class="form-label mt-1" for="typeText">
                                <small class="text-muted">CVV</small>
                            </label>
                        </div>
                    </div>
                </div>
            </form>

            <hr class="my-4">

            <div class="d-flex justify-content-between mb-4">
                <p class="mb-2">Total</p>
                <p class="mb-2">R$ {{ carrinho.total|floatformat:2|intcomma }}</p>
            </div>

            <button type="button" class="btn btn-primary btn-block btn-lg">
                <div class="d-flex justify-content-between">
                    <span>Comprar</span>
                </div>
            </button>
        </div>
    </div>
</div>

base/templates/carrinho/ver.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Carrinho{% endblock %}

{% block cabecalho %}
    {% include "base/cabecalho.html" %}
{% endblock %}

{% block rodape %}
    {% include "base/rodape.html" %}
{% endblock %}

{% block content %}
    <div class="p-3">
        <div class="container">
            <h1 class="mt-2 mb-4 display-6">Carrinho</h1>
        </div>

        <div class="container">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                    <div>
                        <div class="row">
                            <div class="col-lg-7">
                                <h5 class="mb-3">
                                    <a href="{% url 'livro:todos' %}" class="btn btn-secondary">
                                        <i class="fas fa-long-arrow-alt-left me-2"></i>Continuar comprando
                                    </a>
                                </h5>

                                <div class="d-flex justify-content-between align-items-center mb-4">
                                    <p class="mb-0">
                                        Você
                                        {% if itens|length %}
                                            tem {{ itens|length }}
                                            {% if itens|length > 1 %}
                                                itens
                                            {% else %}
                                                item
                                            {% endif %}
                                        {% else %}
                                            não tem itens
                                        {% endif %}
                                        no carrinho.
                                    </p>
                                </div>

                                {% include "carrinho/itens.html" %}
                            </div>

                            {% if itens|length %}
                                {% include "carrinho/pagamento.html" %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}