base/urls.py
from django.urls import path, include

from . import views
from .views import home, sobre

app_name = "base"

urlpatterns = [
    path("contas/", include("django.contrib.auth.urls")),
    path("contas/registrar/", views.registrar, name="register"),
    path("", home, name="home"),
    path("sobre/", sobre, name="sobre")
]

carrinho/urls.py
from django.urls import path
from carrinho import views

app_name = "carrinho"

urlpatterns = [
    path("ver/", views.ver, name="ver"),
    path("adicionar/<int:pk>", views.adicionar, name="adicionar"),
    path("remover/<int:pk>", views.remover, name="remover"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from base import urls as base_urls
from livro import urls as livro_urls
from carrinho import urls as carrinho_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(base_urls)),
    path("livro/", include(livro_urls)),
    path("carrinho/", include(carrinho_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livro/urls.py
from django.urls import path

from . import views

app_name = "livro"

urlpatterns = [
    path("buscar", views.buscar, name="buscar"),
    path("todos", views.todos, name="todos"),
    path("novo", views.novo, name="novo"),
    path("excluir/<int:pk>", views.excluir, name="excluir"),
    path("atualizar/<int:pk>", views.atualizar, name="atualizar"),
    path("vermais/<int:pk>", views.vermais, name="vermais"),
]

base/models.py
from django.db import models

# Create your models here.

livro/models.py
from django.db import models


class TipoParticipacao(models.Model):
    nome = models.CharField("Nome", max_length=200)

    class Meta:
        verbose_name_plural = "Tipos de participação"

    def __str__(self):
        return self.nome


class Pessoa(models.Model):
    nome = models.CharField("Nome", max_length=200)

    class Meta:
        verbose_name_plural = "Pessoas"

    def __str__(self):
        return self.nome


class Categoria(models.Model):
    nome = models.CharField("Nome", max_length=200)
    descricao = models.TextField("Descrição", blank=True, null=True)

    class Meta:
        verbose_name_plural = "Categorias"

    def __str__(self):
        return self.nome


class Editora(models.Model):
    nome = models.CharField("Nome", max_length=200)

    class Meta:
        verbose_name_plural = "Editoras"

    def __str__(self):
        return self.nome


class Livro(models.Model):
    titulo = models.CharField("Título", max_length=200)
    titulo_original = models.CharField(
        "Título original",
        max_length=200,
        blank=True,
        null=True,
    )
    descricao = models.TextField("Descrição", blank=True, null=True)
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text="13 Caracteres <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number</a>",
    )
    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Categoria",
        related_name="livros",
    )
    ano_publicacao = models.CharField(
        "Ano de publicação",
        max_length=200,
        blank=True,
        null=True,
    )
    qtde_paginas = models.IntegerField(
        "Quantidade de páginas",
        blank=True,
        null=True,
    )
    edicao = models.CharField("Edição", max_length=200, blank=True, null=True)
    genero = models.CharField("Gênero textual", max_length=200, blank=True, null=True)
    editora = models.ForeignKey(
        Editora,
        on_delete=models.CASCADE,
        verbose_name="Editora",
        related_name="livros",
    )
    valor = models.DecimalField("Valor", max_digits=7, decimal_places=2, default=0)
    imagem = models.ImageField(upload_to='livro/livro/', blank=True, null=True)

    class Meta:
        verbose_name_plural = "Livros"

    def __str__(self):
        return self.titulo


class Participacao(models.Model):
    livro = models.ForeignKey(
        Livro,
        on_delete=models.CASCADE,
        verbose_name="Livro",
        related_name="participacoes",
    )
    pessoa = models.ForeignKey(
        Pessoa,
        on_delete=models.CASCADE,
        verbose_name="Pessoa",
        related_name="participacoes",
    )
    tipo = models.ForeignKey(
        TipoParticipacao,
        on_delete=models.SET_NULL,
        verbose_name="Tipo",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name_plural = "Participações"

    def __str__(self):
        result = self.pessoa.nome

        if self.tipo:
            result += f" ({self.tipo.nome})"

        return result

base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NovoUsuarioForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NovoUsuarioForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

livro/forms.py
from django import forms
from django.forms import ModelForm

from livro.models import Livro


class LivroForm(ModelForm):
    class Meta:
        model = Livro
        fields = [
            "titulo",
        ]


class BuscarForm(forms.Form):
    isbn = forms.CharField(
        label="ISBN",
        required=True,
        min_length=13,
        max_length=13,
    )

base/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import render, redirect

from base.forms import NovoUsuarioForm
from livro.models import Livro


def home(request):
    livros = Livro.objects.all()[:5]

    dados = {"livros": livros}

    return render(request, "base/home.html", dados)


def sobre(request):


    return render(request, "base/sobre.html")

def registrar(request):
    form = NovoUsuarioForm(request.POST or None)

    if form.is_valid():
        user = form.save()
        login(request, user)
        messages.success(request, "Usuário registrado com sucesso.")

        return redirect("base:login")

    messages.error(request, "Falha ao registrar usuário. Informações inválidas.")

    return render(
        request=request,
        template_name="registration/registrar.html",
        context={"form": form}
    )

livro/views.py
from django.shortcuts import render, redirect

from livro.facade import buscar_no_google_books, criar_livro_do_google_books
from livro.forms import BuscarForm, LivroForm
from livro.models import Livro


def buscar(request):
    form = BuscarForm(request.POST or None)

    resultado = None
    resultado_titulo = None

    if form.is_valid():
        isbn = form.cleaned_data["isbn"]

        if isbn:
            r_json = buscar_no_google_books(isbn)
            livros = r_json.get("items")
            if livros:
                novo_livro = criar_livro_do_google_books(isbn=isbn, json=livros[0])
                resultado = novo_livro.__dict__
                resultado_titulo = novo_livro.titulo

    contexto = {
        "form": form,
        "resultado": resultado,
        "resultado_titulo": resultado_titulo,
    }

    return render(request, "livro/buscar.html", contexto)


def todos(request):
    livros = Livro.objects.all()

    busca = request.POST.get('busca')
    if busca:
        livros = livros.filter(titulo__icontains=busca)

    dados = {
        "livros": livros,
        "busca": busca
    }

    return render(request, "livro/listagem.html", dados)


def novo(request):
    dados = {}

    form = LivroForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("url_listagem")

    dados["form"] = form

    return render(request, "livro/form.html", dados)


def excluir(request, pk):
    livro = Livro.objects.get(pk=pk)
    livro.delete()

    return redirect("livro/todos")


def atualizar(request, pk):
    dados = {}
    livro = Livro.objects.get(pk=pk)
    form = LivroForm(request.POST or None, instance=livro)

    if form.is_valid():
        form.save()
        return redirect("url_listagem")

    dados["form"] = form
    dados["livro"] = livro
    return render(request, "livro/form.html", dados)


def vermais(request, pk):
    dados = {}
    livro = Livro.objects.get(pk=pk)
    dados["livro"] = livro
    return render(request, "livro/vermais.html", dados)

base/templates/livro/atualizar.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Listagem{% endblock %}

{% block content %}
<h1 class="mt-2 mb-4 display-6">Livros</h1>

<ul>
    {% for livro in livros %}
    <li><a href="{% url 'livro:atualizar' livro.id %}">{{livro.titulo}} - {{livro.valor}}</a></li>
    <ul>
        {% for autor in livro.autor.all %}
        <li>{{autor.nome}}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</ul>
<a href="{% url 'livro:novo' %}">
    <button type="submit">Adicionar</button>
</a>
{% endblock %}

base/templates/livro/buscar.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Buscar livro{% endblock %}

{% block content %}
    <h1 class="mt-2 mb-4 display-6">Buscar livro</h1>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-primary mb-3">Salvar</button>
    </form>

    {% if resultado %}
        <p>{{ resultado_titulo }}</p>
        <pre class="mt-3"><code>{{ resultado | pprint }}</code></pre>
    {% elif form.isbn.value %}
        <p>Livro não encontrado.</p>
    {% endif %}
{% endblock %}

base/templates/livro/excluir.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Listagem{% endblock %}

{% block content %}
<h1 class="mt-2 mb-4 display-6">Livros</h1>

<ul>
    {% for livro in livros %}
    <li><a href="{% url 'livro:atualizar' livro.id %}">{{livro.titulo}} - {{livro.valor}}</a></li>
    <ul>
        {% for autor in livro.autor.all %}
        <li>{{autor.nome}}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</ul>
<a href="{% url 'livro:novo' %}">
    <button type="submit">Adicionar</button>
</a>
{% endblock %}

base/templates/livro/form.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}Form{% endblock %}

{% block content %}
<div class="container py-4">
    <form>
        {% csrf_token %}
        <div class="row py-2">
            <div class="col">
                <label for="id_titulo">Título</label>
                {{ form.titulo }}

            </div>
            <div class="col">
                <label for="id_isbn">ISBN</label>
                {{ form.isbn }}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-4">
                <label for="id_autor">Autor</label>
                {{ form.autor }}
            </div>
            <div class="col">
                <label for="id_data_publicacao">Lançamento</label>
                {{ form.data_publicacao }}
            </div>
            <div class="col">
                <label for="id_genero">Genero</label>
                {{ form.genero }}
            </div>
            <div class="col">
                <label for="id_categoria">Categoria</label>
                {{ form.categoria }}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-4">
                <label for="id_descricao">Descrição</label>
                {{ form.descricao }}
            </div>
            <div class="col">
                <label for="id_edicao">Edição</label>
                {{ form.edicao }}
            </div>
            <div class="col">
                <label for="id_editora">Editora</label>
                {{ form.editora }}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-3">
                <label for="id_valor">Preço</label>
                {{ form.valor }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary"> Salvar</button>
    </form>
</div>
{% endblock %}

base/templates/livro/listagem.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Listagem{% endblock %}

{% block cabecalho %}
    {% include "base/cabecalho.html" %}
{% endblock %}

{% block rodape %}
    {% include "base/rodape.html" %}
{% endblock %}

{% block content %}
    <div class="p-3">
        <div class="container">
            <h1 class="mt-2 mb-4 display-6">Livros</h1>
        </div>

        <div class="container mb-5">
            {% block prominence %}
                <form class="d-flex" method="POST" action="{% url 'livro:todos' %}">
                    {% csrf_token %}

                    <div class="input-group mb-3">
                        <input type="text"
                               name="busca"
                               class="form-control"
                               value="{{ busca }}"
                               style="max-width: 15rem;"
                               placeholder="Título do livro"
                               aria-label="Recipient's username"
                               aria-describedby="button-addon2">
                        <button class="btn btn-outline-secondary"
                                type="submit"
                                id="button-addon2">Buscar
                        </button>
                    </div>
                </form>
            {% endblock %}
        </div>

        {% include "livro/livros.html" %}

    <!--
    <div class="container">
        <a href="{% url 'livro:novo' %}">
            <button type="submit">Adicionar</button>
        </a>
    </div>
    -->
    </div>
{% endblock %}

base/templates/livro/livros.html
{% load humanize %}

<div class="album pb-3">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
            {% for livro in livros %}
                <div class="col">
                    <div class="card shadow-sm">
                        <a href="{% url 'livro:vermais' livro.id %}">
                            {% if livro.imagem %}
                                <img src="{{ livro.imagem.url }}"
                                     class="bd-placeholder-img card-img-top object-fit-contain bg-body-secondary"
                                     alt="Imagem de capa do livro"
                                     loading="lazy"
                                     width="100%"
                                     height="225">
                            {% else %}
                                <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image cap"
                                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                                    <rect width="100%" height="100%" fill="#e9ecef"></rect>
                                    <text x="16px" y="50%" fill="#212529" dy=".3em">Sem imagem</text>
                                </svg>
                            {% endif %}
                        </a>
                        <div class="card-body">
                            <p class="card-text">
                                <a href="{% url 'livro:vermais' livro.id %}" class="text-decoration-none text-dark">
                                    {{ livro.titulo }}
                                </a>
                                <small class="text-muted">R$ {{ livro.valor|floatformat:2|intcomma }}</small>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'livro:vermais' livro.id %}"
                                       class="btn btn-sm btn-outline-secondary" role="button">Ver mais</a>
                                    <a href="{% url 'carrinho:adicionar' livro.id %}"
                                       class="btn btn-sm btn-outline-secondary" role="button">Adicionar ao carrinho</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

base/templates/livro/novo.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Listagem{% endblock %}

{% block content %}
<h1 class="mt-2 mb-4 display-6">Livros</h1>

<ul>
    {% for livro in livros %}
    <li><a href="{% url 'livro:atualizar' livro.id %}">{{livro.titulo}} - {{livro.valor}}</a></li>
    <ul>
        {% for autor in livro.autor.all %}
        <li>{{autor.nome}}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</ul>
<a href="{% url 'livro:novo' %}">
    <button type="submit">Adicionar</button>
</a>
{% endblock %}

base/templates/livro/vermais.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Listagem{% endblock %}

{% block cabecalho %}
    {% include "base/cabecalho.html" %}
{% endblock %}

{% block rodape %}
    {% include "base/rodape.html" %}
{% endblock %}


{% block content %}
    <div class="p-3">
        <div class="container">
            <div class="row my-4">
                <div class="col-md-7 order-md-2">
                    <h1>{{ livro.titulo }}</h1>
                    <ul>
                        <li>Descrição: {{ livro.descricao }}</li>
                        <li>Editora: {{ livro.editora }}</li>
                        <li>Edição: {{ livro.edicao }}</li>
                        <li>Quantidade de páginas: {{ livro.qtde_paginas }}</li>
                        <li>Valor: {{ livro.valor }}</li>
                    </ul>
                     <a href="{% url 'carrinho:adicionar' livro.id %}"
                                       class="btn btn-sm btn-outline-secondary" role="button">Adicionar ao carrinho</a>
                    <p class="lead"></p>
                </div>
                <div class="col-md-5">
                    {% if livro.imagem %}
                        <img src="{{ livro.imagem.url }}"
                             class="bd-placeholder-img card-img-top object-fit-contain bg-body-secondary"
                             alt="Imagem de capa do livro"
                             loading="lazy"
                             width="100%"
                             height="500">
                    {% else %}

                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image cap"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#e9ecef"></rect>
                        <text x="16px" y="50%" fill="#212529" dy=".3em">Sem imagem</text>
                    </svg>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}