base/urls.py
from django.urls import path, include

from . import views
from .views import home, sobre

app_name = "base"

urlpatterns = [
    path("contas/", include("django.contrib.auth.urls")),
    path("contas/registrar/", views.registrar, name="register"),
    path("", home, name="home"),
    path("sobre/", sobre, name="sobre")
]

carrinho/urls.py
from django.urls import path
from carrinho import views

app_name = "carrinho"

urlpatterns = [
    path("ver/", views.ver, name="ver"),
    path("adicionar/<int:pk>", views.adicionar, name="adicionar"),
    path("remover/<int:pk>", views.remover, name="remover"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from base import urls as base_urls
from livro import urls as livro_urls
from carrinho import urls as carrinho_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(base_urls)),
    path("livro/", include(livro_urls)),
    path("carrinho/", include(carrinho_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livro/urls.py
from django.urls import path

from . import views

app_name = "livro"

urlpatterns = [
    path("buscar", views.buscar, name="buscar"),
    path("todos", views.todos, name="todos"),
    path("novo", views.novo, name="novo"),
    path("excluir/<int:pk>", views.excluir, name="excluir"),
    path("atualizar/<int:pk>", views.atualizar, name="atualizar"),
    path("vermais/<int:pk>", views.vermais, name="vermais"),
]

base/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NovoUsuarioForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NovoUsuarioForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

base/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import render, redirect

from base.forms import NovoUsuarioForm
from livro.models import Livro


def home(request):
    livros = Livro.objects.all()[:5]

    dados = {"livros": livros}

    return render(request, "base/home.html", dados)


def sobre(request):


    return render(request, "base/sobre.html")

def registrar(request):
    form = NovoUsuarioForm(request.POST or None)

    if form.is_valid():
        user = form.save()
        login(request, user)
        messages.success(request, "Usuário registrado com sucesso.")

        return redirect("base:login")

    messages.error(request, "Falha ao registrar usuário. Informações inválidas.")

    return render(
        request=request,
        template_name="registration/registrar.html",
        context={"form": form}
    )

base/templates/base/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Livraria · {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="Aplicação para controle e venda de livros feita na disciplina de desenvolvimento web back-end">
    <meta name="author" content="Alunos da disciplina de desenvolvimento web back-end">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
{% block cabecalho %}{% endblock %}

{% block content %}{% endblock %}

{% block rodape %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>
</html>

base/templates/base/cabecalho.html
{% load static %}
<style>
    header {
        background:#51413E;
        color: red;
    }
    header a:not(.btn),
    header .btn-link {
        color: #FFEAC9 !important;
    }
</style>
<header class="p-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between">
            <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-decoration-none">
                <img src="{% static 'img/livro.png' %}" height="40" alt="">
                <span class="fs-4">Livraria</span>
            </a>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'base:home' %}" class="nav-link px-2">Início</a></li>
                <li><a href="{% url 'base:sobre' %}" class="nav-link px-2">Sobre</a></li>
                <li><a href="{% url 'livro:todos' %}" class="nav-link px-2">Livros</a></li>
                <li><a href="{% url 'carrinho:ver' %}" class="nav-link px-2">Carrinho</a></li>
                <!--
                <li><a href="{% url 'livro:buscar' %}" class="nav-link px-2">Buscar livro</a></li>
                -->
            </ul>

            {% if user.is_authenticated %}
            <div class="col-md-3 text-end">
                <a class="btn btn-link" href="{% url 'base:logout' %}" role="button">Sair</a>
            </div>
            {% else %}
            <div class="col-md-3 text-end">
                <a class="btn btn-outline-light me-2" href="{% url 'base:login' %}" role="button">Entre</a>
                <a class="btn btn-warning" href="{% url 'base:register' %}" role="button">Crie a sua conta</a>
            </div>
            {% endif %}
        </div>
    </div>
</header>

base/templates/base/home.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Início{% endblock %}

{% block cabecalho %}
{% include "base/cabecalho.html" %}
{% endblock %}

{% block rodape %}
{% include "base/rodape.html" %}
{% endblock %}

{% block content %}
<div class="container col-xxl-8 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <div class="col-10 col-sm-8 col-lg-6">
            <img src="{% static 'img/hero-1.jpg' %}"
                 class="d-block mx-lg-auto img-fluid"
                 alt="Criança preta segurando 6 livros sobre a cabeça"
                 loading="lazy"
                 width="700"
                 height="500">
        </div>
        <div class="col-lg-6">
            <figure>
                <blockquote class="blockquote">
                    <p>
                        Não basta saber ler que "Eva viu a uva". É preciso compreender qual a posição
                        que Eva ocupa no seu contexto social, quem trabalha para produzir a uva e quem
                        lucra com esse trabalho.
                    </p>
                </blockquote>
                <figcaption class="blockquote-footer pt-2">
                    Paulo Freire em <cite title="Pedagogia do Oprimido">Pedagogia do Oprimido</cite>
                </figcaption>
            </figure>
        </div>
    </div>
</div>
<div class="bg-light py-5">
    <div class="container">
        <h1 class="mt-1 mb-4 display-6">Livros</h1>
    </div>
    {% include "livro/livros.html" %}
</div>
{% endblock %}

base/templates/base/rodape.html
<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Início</a></li>
            <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Sobre</a></li>
            <li class="nav-item"><a href="{% url 'livro:todos' %}" class="nav-link px-2 text-muted">Livros</a></li>
        </ul>
        {% include "base/texto_rodape.html" %}
    </footer>
</div>

base/templates/base/sobre.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Sobre{% endblock %}

{% block cabecalho %}
{% include "base/cabecalho.html" %}
{% endblock %}

{% block rodape %}
{% include "base/rodape.html" %}
{% endblock %}

{% block content %}

<div class="container col-xxl-8 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <div class="col-10 col-sm-8 col-lg-6">

        </div>
        <div class="col-lg-6">
            <figure>
                <blockquote class="blockquote">
                    <p>
                    <h2>Sobre:</h2>
                    Website de e-commerce voltado para vendas de livros, com opções de gêneros e preços diversos para todos os publicos.
                    </p>
                </blockquote>
                <figcaption class="blockquote-footer pt-2">
                    Turma de desenvolvimento web - Backend
                </figcaption>
            </figure>
        </div>
    </div>

{% endblock %}

base/templates/base/texto_rodape.html
<p class="text-center text-muted">
    <a href="https://www.pe.senac.br/"
       class="link-secondary"
       title="Serviço Nacional de Aprendizagem Comercial - Regional Pernambuco">
        SENAC PE</a> · Desenvolvimento Web Backend
</p>